# Generated by Django 4.2.3 on 2023-07-22 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_address_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address_id",
            new_name="aaddress_id",
        ),
    ]
