# Generated by Django 4.2.3 on 2023-07-22 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_address_id_user_aaddress_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="aaddress_id",
            new_name="address_id",
        ),
    ]
