# Generated by Django 4.2.3 on 2023-07-24 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_aaddress_id_user_address_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address_id",
        ),
    ]
