# Generated by Django 4.2.3 on 2023-07-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0002_advertisements_remove_car_user_id"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="car",
        ),
        migrations.AddField(
            model_name="comment",
            name="Advertisement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisements.advertisements",
            ),
        ),
    ]
