# Generated by Django 4.2.3 on 2023-07-24 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_remove_comment_car_comment_advertisement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Advertisement",
            new_name="advertisement",
        ),
    ]
