# Generated by Django 4.2.3 on 2023-07-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=60)),
                ("model", models.CharField(max_length=120)),
                ("year", models.IntegerField(default=True, null=True)),
                ("fuel", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
                ("quilometers", models.IntegerField(null=True)),
                ("price", models.IntegerField(null=True)),
                ("cover_img", models.CharField(max_length=150)),
                ("description", models.TextField(max_length=250)),
                ("is_avaliable", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="car",
            name="user_id",
        ),
    ]
