# Generated by Django 4.2.3 on 2023-07-24 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0002_advertisements_remove_car_user_id"),
        ("comments", "0002_remove_comment_car_comment_advertisement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.AddField(
            model_name="advertisements",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
