# Generated by Django 4.2.3 on 2023-07-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0003_delete_car_advertisements_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisements",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
