# Generated by Django 4.2.3 on 2023-07-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0004_alter_advertisements_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisements",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="advertisements",
            name="color",
        ),
        migrations.RemoveField(
            model_name="advertisements",
            name="cover_img",
        ),
        migrations.RemoveField(
            model_name="advertisements",
            name="fuel",
        ),
        migrations.RemoveField(
            model_name="advertisements",
            name="is_avaliable",
        ),
        migrations.RemoveField(
            model_name="advertisements",
            name="model",
        ),
        migrations.RemoveField(
            model_name="advertisements",
            name="quilometers",
        ),
        migrations.AddField(
            model_name="advertisements",
            name="announcementType",
            field=models.CharField(default="SALE", max_length=255),
        ),
        migrations.AddField(
            model_name="advertisements",
            name="km",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advertisements",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advertisements",
            name="title",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="advertisements",
            name="vehicleType",
            field=models.CharField(
                choices=[
                    ("car", "Car"),
                    ("motorcycles", "Motorcycles"),
                    ("auctions", "Auctions"),
                ],
                default="auctions",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="advertisements",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="advertisements",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageUrl", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="advertisements.advertisements",
                    ),
                ),
            ],
        ),
    ]
